name: Push Info (data/hora + usuário)

on:
  push:
  workflow_dispatch:

jobs:
  push-info:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Mostrar data e hora do push (timezone São Paulo)
        run: |
          echo "=== Data/Hora (America/Sao_Paulo) ==="
          TZ="America/Sao_Paulo" date +"%Y-%m-%d %H:%M:%S %Z"

      - name: Mostrar usuário do push
        run: |
          echo "=== Informações do Push ==="
          echo "Actor: ${{ github.actor }}"
          echo "Pusher: ${{ github.event.pusher.name }}"
          echo "Email: ${{ github.event.pusher.email }}"
