name: Push Info (data/hora + usuário)

on:
  push:
  workflow_dispatch:

jobs:
  push-info:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Mostrar data e hora do push (timezone São Paulo)
        run: |
          echo "=== Data/Hora (America/Sao_Paulo) ==="
          TZ="America/Sao_Paulo" date +"%Y-%m-%d %H:%M:%S %Z"
